### ISSUE TITLE
mdshare fetch break: AttributeError: module 'ipywidgets' has no attribute 'version_info'

### ISSUE THREAD

**Issue by jamesdalg** [markovmodel/mdshare#20]
```
python
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mdshare
>>> import numpy as np
>>> 
>>> local_filename = mdshare.fetch('alanine-dipeptide-3x250ns-backbone-dihedrals.npz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jd/mambaforge/lib/python3.10/site-packages/mdshare/api.py", line 121, in fetch
    pg.register(
  File "/home/jd/mambaforge/lib/python3.10/site-packages/progress_reporter/reporter.py", line 252, in register
    self._progress_register(amount_of_work=amount_of_work, description=description, stage=stage, tqdm_args=tqdm_args)
  File "/home/jd/mambaforge/lib/python3.10/site-packages/progress_reporter/reporter.py", line 138, in _progress_register
    if _attached_to_ipy_notebook_with_widgets():
  File "/home/jd/mambaforge/lib/python3.10/site-packages/progress_reporter/reporter.py", line 10, in wrapper
    f.res = f()
  File "/home/jd/mambaforge/lib/python3.10/site-packages/progress_reporter/reporter.py", line 20, in _attached_to_ipy_notebook_with_widgets
    if ipywidgets.version_info[0] < 4:
AttributeError: module 'ipywidgets' has no attribute 'version_info'
>>> with np.load(local_filename) as fh:
...     trajs = [fh[key] for key in sorted(fh.keys())]
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'local_filename' is not defined

```

**Comment by GSINGH006** [comment]
hi @jamesdalg are you still getting this error? I am facing same issue

**Comment by ramansbach** [comment]
A little googling suggests that 'version_info' is now deprecated and would need to be updated to use the more general '.__version__' attribute
